services:
  estimate-host:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gtmotive-estimate-host
    ports:
      - "8080:8080"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - MongoDb__ConnectionString=mongodb://admin:admin123@mongo:27017/?authSource=admin
      - MongoDb__MongoDbDatabaseName=estimate-db

    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - estimate-network

  mongo:
    image: mongo:7.0
    container_name: gtmotive-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=estimate-db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: unless-stopped
    networks:
      - estimate-network

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: gtmotive-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - estimate-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  estimate-network:
    driver: bridge